apiVersion: apps/v1
kind: Deployment
metadata:
  name: membermicroservicedp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: membermicroservice
  template:
    metadata:
      labels:
        app: membermicroservice
    spec:
      containers:
      - name: memberrepos
        image: claimmanagementcr.azurecr.io/memberrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: membermicroservicedp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: membermicroservice